services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: doakiDB
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    command: ["npx", "tsx", "watch", "src/server.ts"]

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: doakiDB
    volumes:
      - postgres-17:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-17:


