services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:root@postgres:5432/doakiDB
      FRONTEND_URL: http://localhost:3000
      PG_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: doakiDB
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: doakiDB
    volumes:
      - postgres-17:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-17:


